layout_spectrum: 0.7168459
color:
  saturation: 0.1738351
  lightness: 0.6433692
  brandStrength: 0
  brandColors:
    - '#90B5CF'
    - '#506664'
    - '#F5F6F9'
    - '#041620'
    - '#F30037'
  rhythmicContrast: 0.2562724
typography_spectrum: 0.9103943
name: Skorka Photography
